plugins {
    id 'com.android.application'
}

android {
    namespace 'com.myfootballcareer.game'
    compileSdk 35

    signingConfigs {
        stableDev {
            storeFile file('../android-dev.keystore')
            storePassword 'mfc-dev-2026'
            keyAlias 'mfcdev'
            keyPassword 'mfc-dev-2026'
        }
    }

    defaultConfig {
        applicationId 'com.myfootballcareer.game'
        minSdk 24
        targetSdk 35
        versionCode 10002
        versionName '1.0.2'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.stableDev
        }
    }
}
